[package]
name = "jikan"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "2.0.17"
rayon = { version = "1.10.0" }
colored = "3.0.0"
serde = { version = "1.0.214", features = ["derive"] }
clap = { version = "4.5.20", features = ["derive"] }
itertools = "0.14.0"
